name: Run Selenium Tests

on:
  push:
    branches:
      - demo  # Change this to your default branch if different
    paths:
      - 'seleniumExecution/src/main/java/App.java'

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'  # Specify the Java version you need

      - name: Start Selenium server
        run: |
          docker run -d --rm -p 4444:4444 --name selenium-chrome selenium/standalone-chrome:latest

      - name: Build and run Selenium tests
        run: |
          cd seleniumExecution
          mkdir -p test-output
          FILE_NAME=reportName.properties

          getProperty() {
            prop_key=$1
            prop_value=$(cat ${FILE_NAME} | grep ${prop_key} | cut -d'=' -f2)
          }

          getProperty reportName
          cd test-output
          > ${prop_value}.txt
          cd ..
          mvn test -DsuiteXmlFile=testng.xml >> ./test-output/${prop_value}.txt 

      - name: List Files
        if: always()
        run: |
          cd seleniumExecution
          echo "ls selenium output"
          ls
          echo
          echo "ls test-output"
          cd test-output
          ls

      - name: Stop Selenium server
        run: docker stop selenium-chrome
