name: Run Selenium Tests

on:
  push:
    branches:
      - demo1  # Change this to your default branch if different
    paths:
      - 'seleniumExecution/src/main/java/App.java'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull GCR Docker Image
      run: docker pull gcr.io/g-code-editor/my-java-maven-chromedriver-image:latest

    - name: Download Chrome Stable Version
      run: |
        curl -o chrome-linux64.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chrome-linux64.zip
      shell: bash

    - name: Unzip Chrome
      run: |
        unzip chrome-linux64.zip -d chrome-linux64
        export CHROME_BIN=$(pwd)/chrome-linux64/chrome
        echo "export CHROME_BIN=$CHROME_BIN" >> $GITHUB_ENV
      shell: bash

    - name: Display Chrome Path
      run: |
        echo "Chrome binary path: $CHROME_BIN"
      shell: bash

    - name: Check ChromeDriver Setup
      run: |
        if [[ -n "$CHROME_BIN" ]]; then
          echo "ChromeDriver is set up in the image."
        else
          echo "ChromeDriver is not set up in the image."
          exit 1  # Exit with an error code if ChromeDriver is not set up
        fi
      shell: bash
      
    - name: Build and run Selenium tests
      run: |
          cd seleniumExecution
          mkdir test-output
          FILE_NAME=reportName.properties

          getProperty() {
            prop_key=$1
            prop_value=$(cat ${FILE_NAME} | grep ${prop_key} | cut -d'=' -f2)
          }

          getProperty reportName
          cd test-output
          > ${prop_value}.txt
          cd ..
          mvn clean install
          mvn test -DsuiteXmlFile=testng.xml >> ./test-output/${prop_value}.txt
      shell: bash
        
    - name: list files
      if: always()
      run: |
          ls
         

