name: Run Selenium Tests

on:
  push:
    branches:
      - demo  # Change this to your default branch if different
    paths:
      - 'seleniumExecution/src/main/java/App.java'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    container:
      image: gcr.io/g-code-editor/my-java-maven-chromedriver-image:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH_KEY }}
          export_default_credentials: true

      - name: Authenticate with Google Container Registry
        run: |
          echo ${GCLOUD_AUTH_KEY} | gcloud auth activate-service-account --key-file=-
          gcloud auth configure-docker

      - name: Build and run Selenium tests
        run: |
          cd seleniumExecution
          mkdir test-output
          FILE_NAME=reportName.properties

          getProperty() {
            prop_key=$1
            prop_value=$(cat ${FILE_NAME} | grep ${prop_key} | cut -d'=' -f2)
          }

          getProperty reportName
          cd test-output
          > ${prop_value}.txt
          cd ..
          mvn test -DsuiteXmlFile=testng.xml >> ./test-output/${prop_value}.txt
        shell: bash

      - name: List files
        if: always()
        run: |
          cd seleniumExecution
          echo "ls selenium output"
          ls
          echo
          echo "ls test-output"
          cd test-output
          ls

      - name: Check for compile errors and upload report
        if: always()
        run: |
          mvn test -DsuiteXmlFile=testng.xml
