name: Run Selenium Tests

on:
  push:
    branches:
      - demo  # Change this to your default branch if different
    paths:
      - 'seleniumExecution/src/main/java/App.java'

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Start Selenium Server
        run: |
          docker run -d -p 4444:4444 --name selenium-chrome selenium/standalone-chrome:latest

      - name: Run Selenium Tests in Headless Mode
        run: |
          cd your-selenium-project-directory
          mvn clean test -Dwebdriver.chrome.driver=/usr/bin/chromedriver -Dchromeoptions.args=--headless

      - name: Stop Selenium Server
        run: docker stop selenium-chrome
