name: Run Selenium Tests

on:
  push:
    branches:
      - beta1  # Change this to your default branch if different
    paths:
      - 'seleniumExecution/src/main/java/App.java'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/gem-rahuladhikari/my-java-maven-chromedriver-image:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run Selenium tests
        run: |
          cd seleniumExecution
          mkdir test-output
          FILE_NAME=reportName.properties

          getProperty() {
            prop_key=$1
            prop_value=$(cat ${FILE_NAME} | grep ${prop_key} | cut -d'=' -f2)
          }

          getProperty reportName
          cd test-output
          > ${prop_value}.txt
          cd ..
          mvn test -DsuiteXmlFile=testng.xml >> ./test-output/${prop_value}.txt
        shell: bash

      - name: List files
        if: always()
        run: |
          cd seleniumExecution
          echo "ls selenium output"
          ls
          echo
          echo "ls test-output"
          cd test-output
          ls

      - name: Check for compile errors and upload report
        if: always()
        run: |
          mvn test -DsuiteXmlFile=testng.xml
