name: Run Selenium Tests

on:
  push:
    branches:
      - demo1  # Change this to your default branch if different
    paths:
      - 'seleniumExecution/src/main/java/App.java'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: 417ccbad5803215181214afa3f91920a2da47e06
        project_id: g-code-editor

    - name: Authenticate with GCR
      run: |
        echo 417ccbad5803215181214afa3f91920a2da47e06 > /tmp/gcr-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcr-key.json
        gcloud --quiet auth configure-docker

    - name: Pull GCR Docker Image
      run: docker pull gcr.io/g-code-editor/gcr.io/g-code-editor/my-java-maven-chromedriver-image:latest

    - name: Use the Docker Image
      run: |
        docker run gcr.io/g-code-editor/gcr.io/g-code-editor/my-java-maven-chromedriver-image:latest
      #     mvn test -DsuiteXmlFile=testng.xml
